baseURL = "https://savannahriverwoodturners.org/"
languageCode = "en-us"
title = "Savannah River Woodturners Club"
# theme = "your-theme-here"  # uncomment after choosing a theme

[params]
  description = "Come join the CSRA's finest group of wood turners."
  logo = "/img/srwoodturners-logo.jpg"

[menu]
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 10
  [[menu.main]]
    name = "Club Officers"
    url = "/club-officers/"
    weight = 15
  [[menu.main]]
    name = "Meeting Dates"
    url = "/meeting-dates/"
    weight = 20
  [[menu.main]]
    name = "Club History"
    url = "/club-history/"
    weight = 30
  [[menu.main]]
    name = "Meeting Posts"
    url = "/posts/"
    weight = 40
  [[menu.main]]
    name = "Submit Minutes"
    url = "/submit-minutes/"
    weight = 50

[permalinks]
  posts = "/posts/:year/:month/:slug/"
